### PR TITLE
Feature/clean up

### PR DESCRIPTION
**Pull request by 38leinaD**
Remove custom Base64 class. Use the platform.

### CODE REVIEW

**Comment by hczedik** [comment]
Hi @38leinaD,
I'm afraid, to my knowledge, none of the original creators are using and maintaining WarpUnit any more.
Do you want to become the maintainer?

If @gunterze and @rawmahn agree I can give you write access to this repository, and you can merge these requests yourself.

**Comment by gunterze** [comment]
No objections from my side.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rawmahn** [comment]
I believe it's still used in a few projects, but yeah, not really
maintained.
No objections from my side :)

cheers,
Roman

**Comment by 38leinaD** [comment]
I would really like to see this library stay alive. I am fine with merging the pull requests myself if you give me permission.

**Comment by hczedik** [comment]
@38leinaD I have invited you to a WarpUnit-Maintainers team. You should then have the rights to write to the repository.
Willkommen Daniel!

**Comment by 38leinaD** [comment]
Thanks for the trust! :-)

**Pull request merged**
